### ISSUE TITLE
New version broke pritunl fake api

### ISSUE THREAD

**Issue by cfouche3005** [simonmicro/Pritunl-Fake-API#16]
`[ERROR] Failed to check notifications
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/runners/updates.py", line 25, in _check_updates
    response = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by simonmicro** [comment]
This was a bug inside by Cloudflare configuration. It should be fixed now...
