### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by qwertyhq0x** [simonmicro/Pritunl-Fake-API#26]
When I run Setup.py and start installation, an error appears:

```
  ____       _ _               _   _____     _             _    ____ ___ 
 |  _ \ _ __(_) |_ _   _ _ __ | | |  ___|_ _| | _____     / \  |  _ \_ _|
 | |_) | '__| | __| | | | '_ \| | | |_ / _` | |/ / _ \   / _ \ | |_) | | 
 |  __/| |  | | |_| |_| | | | | | |  _| (_| |   <  __/  / ___ \|  __/| | 
 |_|   |_|  |_|\__|\__,_|_| |_|_| |_|  \__,_|_|\_\___| /_/   \_\_|  |___|
                                                                         
[I]nstall, [R]eset, [B]uy Pritunl, [Q]uit? I

By default, the Pritunl API endpoint is hosted at "app.pritunl.com".
In case you want to use your own instance, you also have to support HTTPS!
Note, that the SSO implementation of Pritunl is hosted at their servers (closed source) and will just be "disabled".
Please enter the new API endpoint [pritunl-api.simonmicro.de]: pritunl-api.simonmicro.de
Okay. We will change "app.pritunl.com" to "pritunl-api.simonmicro.de" and "auth.pritunl.com" to "pritunl-api.simonmicro.de/auth/" now...
[1/7] Replacing in /usr/lib/python3.8...
[2/7] Replacing in /usr/lib/python3...
[3/7] Replacing in /usr/lib/python3.9...
[4/7] Replacing in /usr/lib/pritunl/...
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    doTheReplace(originalApiServer, ownApiServer, originalAuthServer, ownApiServer + '/auth/')
  File "setup.py", line 49, in doTheReplace
    fh = open(os.path.join(p, ff), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/pritunl/include/python3.6m'
root@pritunl:~/Pritunl-Fake-API-master-2/server# 
```

**Comment by simonmicro** [comment]
Huh? That's strange... Were you running an update during this? Did something modify the files during this? What is the output of these:

```bash
ls -la /usr/lib/pritunl/include
ls -la /usr/lib/pritunl/include/python*
ls -la /usr/lib/pritunl/include/python3.6m
readlink /usr/lib/pritunl/include/python3.6m
```

Could it be that `/usr/lib/pritunl/include/python3.6m` is a broken link on you OS?

**Comment by qwertyhq0x** [comment]
Do you think there's a problem in Python?
I didn't put any updates, now I'll try on a new host
