### ISSUE TITLE
[ERROR] Failed to check notifications

### ISSUE THREAD

**Issue by JamesHawkinss** [simonmicro/Pritunl-Fake-API#31]
Hi there, thanks for making such a great project! Everything is working well, except our logs are being filled up with these errors from all hosts.

We're hosting our own instance of the Fake API server, is this a known error?

Pritunl version: v1.32.3602.80 d1b072

Thanks!

```
[redacted][2023-10-03 11:49:59,237][ERROR] Failed to check notifications
Traceback (most recent call last):
  File "/usr/lib/pritunl/usr/lib/python3.9/site-packages/pritunl/runners/updates.py", line 25, in _check_updates
    response = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/pritunl/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by simonmicro** [comment]
Hmm, this is strange. It seems like Cloudflare is blocking your requests. I have deployed a rule to soften the WAF (web-application-firewall), I hope this helps.

**Comment by JamesHawkinss** [comment]
Hi @simonmicro, we're using a self-hosted version of the API server behind Cloudflare, could you let me know the WAF rule you set so I can duplicate it on our setup? Thanks!

**Comment by simonmicro** [comment]
Meh - basically, if you access the CNAME of the API: Skip. I therefore just use Cloudflare for acceleration and load balancing...
